backend:
  name: git-gateway
  repo: Malvolio/nautilus-trial
  repository branch: master
  local_backend: true

local_backend:
  url: http://localhost:8081/api/v1

media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    identifier_field: "slug"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Date line", name: "dateline", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    identifier_field: "slug"
    fields:
      - { label: "Headline", name: "headline", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Date line", name: "dateline", widget: "string" }
      - { label: "Before the jump", name: "summary", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }
